### PR TITLE
add in testcontainers so that contributors do not need to run a replica set locally

### PR DESCRIPTION
**Pull request by dberry-rcs**
This makes life easier for contributors. No need to have a local database with replica sets turned on. Also, I use MongoAtlas and do not usually keep a local mongodb.

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
would it be possible to make testcontainers/docker optin somehow?
i personally hate having to waste disk space for docker/images on my dev machine. so i don't have docker installed unless i'm investigating something related to docker in particular. and the tests execute faster with a local mongo instance compared to letting testcontainers spin up docker containers imho.

**Comment by dberry-rcs** [comment]
I'll take a look @dj-nitehawk. Is an env variable acceptable for triggering the db source with local mongo being the default?

**Comment by dberry-rcs** [comment]
@dj-nitehawk On a separate note, I am seeing the I64 test fail again once in awhile. Are you okay with me changing the order of the tests so I can try and avoid whatever race condition is occurring?

**Comment by dberry-rcs** [comment]
> I'll take a look @dj-nitehawk. Is an env variable acceptable for triggering the db source with local mongo being the default?

I have checked this in. It is now conditional on an evironment variable 'MONGODB_ENTITIES_TESTCONTAINERS' being set to some value, i.e. 'TRUE' if it is not set it will default to a local copy of mongodb

**Comment by dj-nitehawk** [comment]
looks good...
thanks!

**Pull request merged**
