### PR TITLE
Added CreatedOn Property

### PR DESCRIPTION
**Pull request by ehigiepaul**
@dj-nitehawk Thank for this amazing package. I have been using it for awhile and noticed that on every creation of a new document the ModifiedOn date is added.

I created a CreatedOn property to separate the created document from the modified ones which will help with some easy sorting of update documents from created and it will also help in the watcher feature you recently added.

Please kindly review.

Thanks and I wish you a wonderful day.

### CODE REVIEW

**Comment by schauhan232** [comment]
Out of the scope of PR, but just to get an attention, with `DB.` looks like we are injecting hard dependency instead of interface, this is stopping me while I think writing unit test to mock behavior of `DB.` , Do anyone have work around or thought to resolve this issue ?

**Comment by schauhan232** [comment]
@ehigiepaul I think you need to write unit test for this to understand the new behavior 🙂

**Comment by dj-nitehawk** [comment]
@ehigiepaul thanks for the PR but...

there's a couple of reasons why i'm reluctant to add another date property to the `IEntity` interface.

1. some folks don't like even the `ModifiedOn` property forced upon them. 
ex: #48 and some folks i work with absolutely hate the `ModifiedOn` property being there on each and every record. i personally also don't want a `CreatedOn` property on every record, because it does take up storage space.

2. if the goal is to get entities sorted by creation date, you can easily use the `ID` property for that like so:
```csharp
    DB.Find<Author>()
        .Match(_ => true)
        .Sort(a => a.ID, Order.Descending)
        .Execute();
```

3. since the creation date/time is embedded in the objectid of an entity, you can access it like so:
```csharp
    ObjectId.Parse(author.ID).CreationTime
```

4. if you need to differentiate between created vs. modified when using watchers, you could either use separate watchers for "created" & "updated" events. or try something like this:
```csharp
    authors.Where(a =>
                  a.ModifiedOn
                   .Subtract(ObjectId.Parse(a.ID)
                   .CreationTime)
                   .TotalSeconds < 1);
```

5. i also have an idea to make `ModifiedOn` property optional. so if that experiment works, i can make `CreatedOn` optional the same way.

**Comment by ehigiepaul** [comment]
@dj-nitehawk Thanks for the breakdown. I see the angle your head and its really understandable. 

Then it will be preferable ModifiedOn property to be optional giving user design control and I noticed even if users try to overwrite the ModifiedOn property it doesn't change because of the force declaration in the SaveAsync method at the DB.save. 

I just pushed a request to fix this and making the ModifiedOn and CreatedOn to be optional.

**Comment by dj-nitehawk** [comment]
I'm not at a computer right now to check this properly. but I don't think making ModifiedOn nullable and not setting a value on save isn't really gonna cut it. for example on update the value will get set by the library. last time I checked ModifiedOn had 60+ references in the code. give me a day or two to try and implement my idea for giving the user the choice have these properties on their entities and have the library set the values automatically where appropriate.

**Comment by dj-nitehawk** [comment]
created an experimental branch to work on this. let's see how we go...

**Comment by ehigiepaul** [comment]
Ok cool.

**Comment by dj-nitehawk** [comment]
@ehigiepaul the experiment was successful. just published v14. [here's how to use it](https://github.com/dj-nitehawk/MongoDB.Entities/wiki/02.-Entities#optional-auto-managed-properties).
it will however require existing code that uses the `ModifiedOn` property to add and implement `IModifiedOn` interface to the entity definitions.

**Pull request merged**
