### PR TITLE
Update Many.cs

### PR DESCRIPTION
**Pull request by UsmanSabir**
Multi-database error fix with Relationships

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
can you show me how to reproduce the error you're seeing?

**Comment by UsmanSabir** [comment]
1- In library1, I initialized DB with entity1. Entity database is set by following https://mongodb-entities.com/wiki/Multiple-Databases.html
2- In library2, I initialized DB with entity2. entity2 has one to many relation and entity2 database is also set. Ref: https://mongodb-entities.com/wiki/Relationships-Referenced.html
3- during execution, entity2 was being saved in library1 db collection. While debuging, figured out this issue.

I am using .Net Core 3.1

**Comment by dj-nitehawk** [comment]
are you trying to do cross-database relationships? 
if so, it is not supported, as [mentioned in the wiki](https://mongodb-entities.com/wiki/Multiple-Databases.html#limitations).
i'm sorry i still can't understand the problem. i'm a bit tapped out of brain power today, so a small code sample will help.
thanks!

**Comment by UsmanSabir** [comment]
Project modules are complex. here is the recorded video of issue I am facing. I am NOT working with cross-database relationship. both parent child are withing same db.
https://drive.google.com/file/d/1j24kU98Ammgi6l2R-HXa6vc1zhNjVM-a/view?usp=sharing

**Comment by dj-nitehawk** [comment]
is this what you're basically doing?
```csharp
using MongoDB.Entities;
using System.Threading.Tasks;

namespace TestApplication
{
    public class User : Entity
    {
        public string Name { get; set; }
        public Many<PasswordHistory> PasswordHistories { get; set; }

        public User()
            => this.InitOneToMany(() => PasswordHistories);
    }

    public class PasswordHistory : Entity
    {
        public string OldPassword { get; set; }
    }

    public static class Program
    {
        private static async Task Main()
        {
            await DB.InitAsync("USER_DB");
            DB.DatabaseFor<User>("USER_DB");
            DB.DatabaseFor<PasswordHistory>("USER_DB");

            var user = new User { Name = "TestUser", };
            await user.SaveAsync();

            var histories = new[]
            {
                new PasswordHistory { OldPassword = "123" },
                new PasswordHistory { OldPassword = "321" }
            };
            await histories.SaveAsync();

            await user.PasswordHistories.AddAsync(histories);
        }
    }
}
```
if so, it works without a problem:
Screenshot

if that's different to what you're trying to do, pls update the above repro so i can run it locally to debug.

**Comment by UsmanSabir** [comment]
issue is recorded and shown in shared video. Busy with other stuff and wouldn't be able to work further on it. closing PR

**Comment by dj-nitehawk** [comment]
i think you've messed up your project references or something. because this feature is working as intended in many other projects.

**Comment by UsmanSabir** [comment]
> i think you've messed up your project references or something. because this feature is working as intended in many other projects.

ok thanks. as a workaround, I used embedded entity instead of reference and it solved my problem for the time being.

**Pull request closed without merging**
