### PR TITLE
Update TestGeoNear.cs

### PR DESCRIPTION
**Pull request by reachej**
FluentGeoNear DistanceField changed to string

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
the expression does get converted to a string in the end:
https://github.com/dj-nitehawk/MongoDB.Entities/blob/10c6591c79176925215e4d8317b3564e6465da40/MongoDB.Entities/DB/DB.GeoNear.cs#L30

everything works fine in mongo server 5.

what version of server are you having trouble with?

can you provide a minimal repro program that demonstrates the issue? pls create a new issue with the repro.

this PR cannot be accepted because it's taking away existing functionality and breaking existing projects.

**Comment by reachej** [comment]
I'm using UiPath connecting to CosmoDB with MongoDB server version 4.2.  I realized I'd added some wrong code/information earlier regarding the includeLocs.

The problem is with the DistanceField. This is what is working:

`
        public static IAggregateFluent<T> FluentGeoNear<T>(Coordinates2D NearCoordinates, string DistanceField, bool Spherical = true, double? MaxDistance = null, double? MinDistance = null, int? Limit = null, BsonDocument Query = null, double? DistanceMultiplier = null, Expression<Func<T, object>> IncludeLocations = null, string IndexKey = null, AggregateOptions options = null, IClientSessionHandle session = null) where T : IEntity
        {
            return new GeoNear<T>
            {
                near = NearCoordinates,
                distanceField = DistanceField,
                spherical = Spherical,
                maxDistance = MaxDistance,
                minDistance = MinDistance,
                query = Query,
                distanceMultiplier = DistanceMultiplier,
                limit = Limit,
                includeLocs = IncludeLocations?.FullPath(),
                key = IndexKey,
            }
            .ToFluent(options, session);
        }
`

AND

`      public IAggregateFluent<T> GeoNear<T>(Coordinates2D NearCoordinates, string DistanceField, bool Spherical = true, int? MaxDistance = null, int? MinDistance = null, int? Limit = null, BsonDocument Query = null, int? DistanceMultiplier = null, Expression<Func<T, object>> IncludeLocations = null, string IndexKey = null, AggregateOptions options = null, bool ignoreGlobalFilters = false) where T : IEntity
        {
            var globalFilter = Logic.MergeWithGlobalFilter(ignoreGlobalFilters, globalFilters, Builders<T>.Filter.Empty);

            if (globalFilter != Builders<T>.Filter.Empty)
            {
                return DB
                    .FluentGeoNear(NearCoordinates, DistanceField, Spherical, MaxDistance, MinDistance, Limit, Query, DistanceMultiplier, IncludeLocations, IndexKey, options, Session)
                    .Match(globalFilter);
            }

            return DB.FluentGeoNear(NearCoordinates, DistanceField, Spherical, MaxDistance, MinDistance, Limit, Query, DistanceMultiplier, IncludeLocations, IndexKey, options, Session);
        }
`

**Comment by reachej** [comment]
I updated/correct the comments on the [dev.to article](https://dev.to/reachej/comment/229i8)  

I'm not trying to store two different entities in the same collection.  From what I've seen, the Collection created for an entity type is always the name of the model capitalized.  

_______________________________________________________________________
If I use the code without my changes, 

DistanceField: x => x.Location 
will run, but I won't get any distances, I only get whatever is stored in at x.Location .  I can put any property there really and it will return whatever is stored there, such as DistanceField:  x => x.Name will return the name

__________________________________________________________________________________________________
If I use the code with my changes 

which are changes to three lines:

In DB.GeoNear.cs:

  public static IAggregateFluent<T> FluentGeoNear<T>(Coordinates2D NearCoordinates, string DistanceField = null, bool Spherical = true, double? MaxDistance = null, double? MinDistance = null, int? Limit = null, BsonDocument Query = null, double? DistanceMultiplier = null, Expression<Func<T, object>> IncludeLocations = null, string IndexKey = null, AggregateOptions options = null, IClientSessionHandle session = null) where T : IEntity

distanceField = DistanceField,


In DBContext.GeoNear.cs:

public IAggregateFluent<T> GeoNear<T>(Coordinates2D NearCoordinates, string DistanceField = null, bool Spherical = true, int? MaxDistance = null, int? MinDistance = null, int? Limit = null, BsonDocument Query = null, int? DistanceMultiplier = null, Expression<Func<T, object>> IncludeLocations = null, string IndexKey = null, AggregateOptions options = null, bool ignoreGlobalFilters = false) where T : IEntity


a query like this gets me the correct distances:

 var results =   DB.FluentGeoNear<ArtGallery >(
                        IndexKey: "location",
                        NearCoordinates: EiffelTower.Location, 
                        DistanceField: "distance_in_meters",
                        DistanceMultiplier:1,
                   //  Spherical: true,
                   //  MinDistance: 5,
                        MaxDistance: 15000 // distance in meters
                         )
                         .ToListAsync().GetAwaiter().GetResult();

Trying to run this with my code changes
DistanceField: x => x.Location 
gives an error.  Also, I think it is a CosmoDB thing possibly, but I have to have the Index key specified or it errors too.
 __________________________________________________________________________________________________

**Comment by dj-nitehawk** [comment]
most likely an cosmosdb related thing. because i just ran the following program and it works just fine on regular mongodb server.

can you chuck that into a new console app and run it targetting cosmosdb to try?

also is there any logging/debugging/profiling method to see the actual query received by cosmosdb?

if so, pls post the actual query.

```cs
using MongoDB.Driver;
using MongoDB.Entities;

await DB.InitAsync("test");

await DB.Index<ArtGallery>()
        .Key(g => g.Location, KeyType.Geo2DSphere)
        .Option(o => o.Background = false)
        .CreateAsync();

await new[]
{
    new ArtGallery {
        Name = "Galleria Le-Pari",
        Location = new Coordinates2D(48.8539241, 2.2913515)
    },
    new ArtGallery {
        Name = "Versailles House Of Art",
        Location = new Coordinates2D(48.796964, 2.137456)
    },
    new ArtGallery {
        Name = "Poissy Arts & Crafts",
        Location = new Coordinates2D(48.928860, 2.046889)
    },
}.SaveAsync();

var locEiffelTower = new Coordinates2D(48.857908, 2.295243);

var results = await DB
    .Find<ArtGallery>()
    .Match(g => g.Location, locEiffelTower, 20000)
    .ExecuteAsync();

foreach (var gallery in results)
{
    Console.WriteLine(gallery.Name);
}

Console.ReadLine();

var results2 = await DB
    .FluentGeoNear<ArtGallery>(
        NearCoordinates: locEiffelTower,
        DistanceField: g => g.DistanceInMeters,
        MaxDistance: 20000)
    .ToListAsync();

foreach (var gallery in results2)
{
    Console.WriteLine($"{gallery.Name} - {gallery.DistanceInMeters / 1000:00.00} KM");
}

Console.ReadLine();

public class ArtGallery : Entity
{
    public string Name { get; set; }
    public Coordinates2D Location { get; set; }
    public double DistanceInMeters { get; set; }
}

public class Tower : Entity
{
    public string Name { get; set; }
    public Coordinates2D Location { get; set; }
    public double DistanceInMeters { get; set; }
}

public enum LocationType
{
    Tower,
    ArtGallery,
    Cafe
}

public class Place : Entity
{
    public LocationType LocationType { get; set; }

    public string Name { get; set; }
    public Coordinates2D Location { get; set; }
    public double DistanceInMeters { get; set; }

}
```

**Comment by reachej** [comment]
Okay underlying problem identified and solved.  

This is the only thing that needs to change in your code to make it work for cosmo (Cosmo can't take a capital letter for a document property that starts with a lowercase letter):

                distanceField = DistanceField?.FullPath().ToLower(),

From what I was actually working with:
var query =   DB.FluentGeoNear<Unlocode_port>(
				    IndexKey: "port_coordinates",
                    NearCoordinates: myport.Port_coordinates, 
                    DistanceField:  x=>x.Distance_in_meters,
		//IncludeLocations: x => x.Distance_in_meters,
					DistanceMultiplier:1,
				//	Spherical: true,
				   // MinDistance: myport.Port_radius_m,
	                 MaxDistance: 1000 // distance in meters
		             ).ToString();
Console.WriteLine(query);

aggregate([{ "$geoNear" : { "near" : { "type" : "Point", "coordinates" : [-78.049999999999997, 33.988888899999999] }, "distanceField" : "Distance_in_meters", "spherical" : true, "maxDistance" : 1000.0, "distanceMultiplier" : 1.0, "key" : "port_coordinates" } }])

**Comment by dj-nitehawk** [comment]
how did the document property become lowercase?
does your entity model not match with the document shape in the db?

**Comment by reachej** [comment]
When I save a new entity, I notice two things:

1.  Assuming the collection doesn't exist for that model, a new one will be created with a capital letter.
2. The properties of the model will always have their first letter lowercased in the database, so technically the code I gave you needs to only lowercase the first letter of an entity property and lowercasing all of them could break things (although I lowercase everything.

image

**Comment by dj-nitehawk** [comment]
is this is cosmosdb behavior? (lowercasing first letter of document properties)
this does not happen with regular mongodb. unless we put a `[Field(...)]` attribute on properties to customize the property names.
weird thing is i've never heard of cosmosdb automatically doing this.
is there some settings in your dashboard where you could turn off such a setting?

**Comment by reachej** [comment]
Its my fault, code doesn't need to be changed on your side.

I found out this line of code I had was causing the capitalization behavior seen:

var camelCaseConvention = new ConventionPack { new CamelCaseElementNameConvention() };
ConventionRegistry.Register("CamelCase", camelCaseConvention, type => true);


I'd originally added it about two/three years ago (its part of MongoDB serialization conventions) because it helped when searching for results so searching for MySearchWord would find mysearchword and didn't seem to cause any problems.  Good to know that's where the behavior was coming from.

**Pull request closed without merging**
