### PR TITLE
Enable the Nullable project property and fix all the warnings

### PR DESCRIPTION
**Pull request by dberry-rcs**
Enabled nullable for just the MongoDB.Entities project. Fixed all the warnings that resulted from the change.

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
made some more improvements with regards to nullables. could you have a quick glance over and see if everything looks ok pls?
if all good, i'll merge to master tomorrow.
i think we will be making the next release a major version jump since there's a possibility this may break some existing code (even though easily fixable). 
after merging the PR, i'll release a beta version so we could take it for a good spin before a public release.
thanks for this! been procrastinating enabling nullable support for a long time ;-)

**Comment by dberry-rcs** [comment]
Cleaned up some warnings that Rider was showing.

**Comment by dj-nitehawk** [comment]
okieee... did some more nullable improvements...
what does rider say now?
i think we're almost there :-)

**Comment by dberry-rcs** [comment]
Resolved the last of the warnings

**Comment by dj-nitehawk** [comment]
good job...
thanks a lot for this...
definitely was a needed change to move the library forward :-)

**Comment by dj-nitehawk** [comment]
pushed a beta release to nuget `v21.0.2.1-beta`

**Comment by dj-nitehawk** [comment]
was just testing out the beta in an existing project and now i'm second guessing the choice to make the `IEntity.ID` nullable.

now i'm thinking that the only time it would be null when the user instantiates an instance themselves and right until it is saved to the db.

so what are the chances that code would be trying to read the `ID` field before the entity is saved. 99% of the time when an entity is retrieved from the db, it would not be null, unless the query code explicity does a projection to exclude the ID. in which case the developer knows it would be null and would take steps to do a null check. or most likely the ID property would not be accessed at all in his code, which is why it was excluded in the first place.

what are your thoughts on this?
shall i make the ID property non-nullable?

**Comment by dberry-rcs** [comment]
I upgraded my existing project to the beta. I had 13 errors to start with and I had to "!" all the ids that I knew would be filled in. 

While I prefer IDs that are not null, the fact that there are 2 use cases where the id can be null means that it should be nullable. It is up to the user of the library to determine if they feel comfortable enough to use "!" on the id. I would rather do this than get a NullPointer Exception

**Comment by dj-nitehawk** [comment]
okiee then... we'll leave the `ID` as nullable...
if you find anymore nullable fixes that are needed, pls send in a new PR.
tc mate!

**Pull request merged**
