### PR TITLE
Removed 'new' constraint on Many<T> relationship

### PR DESCRIPTION
**Pull request by HeroicSoft**
Removed 'new' constraint on Many<T> relationship as it greatly interferes with the MongoDB driver when hydrating/constructing entities which are required to have non-default constructors.

This removes the possibility to add entities to 'Many' relationships by ID.

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
thanks for bringing this to my attention. i managed to solve the problem without having to remove existing features. with the latest version you can now do this:
```csharp
    public class Author : Entity
    {
        public string Name { get; set; }

        [BsonConstructor]
        public Author(string name)
        {
            Name = name;
        }
    }

    public class Book : Entity
    {
        public string Title { get; set; }
        public Many<Author> Authors { get; set; }

        public Book()
        {
            this.InitOneToMany(() => Authors);
        }
    }
```
```csharp
            new DB("test");

            var author = new Author("test author");
            author.Save();

            var book = new Book { Title = "book title" };
            book.Save();
            book.Authors.Add(author);

            var result = book.Authors.ChildrenQueryable().Single();
```

**Comment by HeroicSoft** [comment]
Thanks for the update!

Tho, while the change certainly works, it may cause unintented/unclear errors. A parameterless Activator.CreateInstance call only works if the type in question has a public parameterless default constructor. Otherwise it'll throw.

The better solution would probably be to switch the entity and id based implementations, so no entity instance has to be created in the first place. The JoinCollection isnt bound to the concrete entity type so you could just chain the entity version onto the id version which holds the concrete implementation of updating the JoinRecord.

Furthermore, from a conceptual level, it's arguable if 'Many' should support adding entities by ID in the first place. The problem is that 'Many' acts as a collection, as such you'd expect to add and remove entities instead of working on an ID level.

**Comment by dj-nitehawk** [comment]
> The better solution would probably be to switch the entity and id based implementations
done! thanks for the idea...
>  it's arguable if 'Many' should support adding entities by ID
i get what you mean but myself and a few others are using it in multiple n-tier applications so it would have to remain.

thanks again for your contribution!

**Comment by HeroicSoft** [comment]
Great stuff! Thanks again!

**Pull request closed without merging**
