### PR TITLE
Allow change default db at runtime

### PR DESCRIPTION
**Pull request by debitexpress-business**

### CODE REVIEW

**Comment by debitexpress-business** [comment]
Thank you for this amazing project. If allowed, it will be greatly appreciated if there is a way to change the default database during runtime.

**Comment by dj-nitehawk** [comment]
thank you for the feedback!

pr looks ok on first glance. i will review it properly when i get some free time today or tomorrow.

just need to be sure that changing the default db during runtime won't break any other features of the library like file storage, change-streams, etc. 

have you had a look at how it might effect other parts of the library?

also, may i know the reason behind this requirement to change the default db during runtime? never thought anybody would wanna do that :-)

**Comment by debitexpress-business** [comment]
Thank you for consideration and fast response. :)

Currently I'm working with a project that requires creation of multiple company database with a single application.

The process flow is like this:
1. Create a company database
2. Insert the company created in separate database
3. Get the list of created company
4. Select any company to login and logout if want to change company

I thought with this, I need to change database at runtime since each company should be in a separate database. 
If you thought about this please enlighten me. Thank you so much!! :-)

**Comment by dj-nitehawk** [comment]
i merged your pr into the dev branch and made some improvements to it. but...
when i run the tests in parallel, it results in some unpredictable behavior.
some entities are getting created in incorrect databases when the default db is changed during runtime.

i made an [experimental branch](https://github.com/dj-nitehawk/MongoDB.Entities/tree/experiment-default-db-change) hoping to find a fix for it, but it doesn't seem to be working.

i think the default-db-switching will only work properly if all of your entities are stored in the default db. when different entities are stored in different dbs and then you switch the default db, things are goin bonkers atm.

i will have another crack at it tomorrow as it's past my bedtime right now.

**Comment by dj-nitehawk** [comment]
btw, what type of application are you developing? desktop or server based?

**Comment by dj-nitehawk** [comment]
the main problem is that we need to update the properties of the [generic static Cache\<T> class](https://github.com/dj-nitehawk/MongoDB.Entities/blob/d9e83c1830e65fa5b631ee0f9ea9e3fb2b7a563f/MongoDB.Entities/DB.cs#L220) once the default db is changed. which i have no idea how to do properly.

is it not possible to just restart/reload your application with new connection/db init settings?

**Comment by debitexpress-business** [comment]
Thanks for looking out for this feature, I'm currently developing a desktop application.

I will also look the possibility of simplifying my application by restarting it. Thank you :-)

**Pull request merged**
